import {NgModule} from '@angular/core';
import {DragDropModule} from '@angular/cdk/drag-drop';
import {
    MatSidenavModule,
    MatToolbarModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatTableModule,
    MatChipsModule,
    MatInputModule,
    MatSelectModule,
    MatIconModule,
    MatListModule,
    MatPaginatorModule,
    MatSortModule,
    MatDatepickerModule,
    MatSnackBarModule,
    MatCardModule,
    MatDialogModule,
    MatGridListModule,
    MatCheckboxModule,
    MatStepperModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatMenuModule,
    MatTooltipModule,
    MatRadioModule,
    MatProgressSpinnerModule,
    MatProgressBarModule,
    MatExpansionModule,
    MatTabsModule,
    MatAutocompleteModule
} from '@angular/material';

@NgModule({
    imports: [
        MatTooltipModule,
        MatGridListModule,
        MatCardModule,
        MatDialogModule,
        MatButtonModule,
        MatButtonToggleModule,
        MatSidenavModule,
        MatToolbarModule,
        MatTableModule,
        MatChipsModule,
        MatInputModule,
        MatSelectModule,
        MatIconModule,
        MatListModule,
        MatCheckboxModule,
        MatMenuModule,
        MatPaginatorModule,
        MatSortModule,
        MatDatepickerModule,
        MatSnackBarModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatStepperModule,
        MatRadioModule,
        MatProgressSpinnerModule,
        MatProgressBarModule,
        MatExpansionModule,
        MatTabsModule,
        MatAutocompleteModule,
        DragDropModule
    ],
    declarations: [],
    exports: [
        MatTooltipModule,
        MatGridListModule,
        MatCardModule,
        MatDialogModule,
        MatButtonModule,
        MatButtonToggleModule,
        MatSidenavModule,
        MatToolbarModule,
        MatTableModule,
        MatChipsModule,
        MatInputModule,
        MatSelectModule,
        MatIconModule,
        MatListModule,
        MatCheckboxModule,
        MatMenuModule,
        MatPaginatorModule,
        MatSortModule,
        MatDatepickerModule,
        MatSnackBarModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatStepperModule,
        MatRadioModule,
        MatProgressSpinnerModule,
        MatProgressBarModule,
        MatExpansionModule,
        MatTabsModule,
        MatAutocompleteModule,
        DragDropModule
    ]
})
export class MaterialModule {

}